# Generated by Django 4.2 on 2025-07-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('swap_request', 'Swap Request'), ('swap_accepted', 'Swap Accepted'), ('swap_rejected', 'Swap Rejected'), ('swap_completed', 'Swap Completed'), ('new_rating', 'New Rating'), ('badge_earned', 'Badge Earned'), ('admin_message', 'Admin Message'), ('system', 'System Message')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
