# Generated by Django 4.2 on 2025-07-12 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0002_initial'),
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='skill_offered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_swaps', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='skill_wanted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_in_swaps', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
