# Generated by Django 4.2 on 2025-07-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability',
            field=models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('evenings', 'Evenings'), ('mornings', 'Mornings'), ('flexible', 'Flexible Schedule'), ('busy', 'Currently Busy')], default='flexible', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('guest', 'Guest')], default='user', help_text='User role in the system', max_length=10),
        ),
    ]
